# Generated by Django 4.1.7 on 2023-04-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routepart',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
